name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{matrix.version}} - ${{matrix.os}} - ${{matrix.arch}} - ${{github.event_name}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # See <https://julialang-s3.julialang.org/bin/versions.json> for available Julia versions
        include:
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.8"
          - arch: "x64"
            os: "windows-latest"
            version: "1.8"
          - arch: "x64"
            os: "macOS-latest"
            version: "1.8"
          # Broken (see <https://github.com/jkrumbiegel/GridLayoutBase.jl/issues/42>)
          # - arch: "x86"
          #   os: "ubuntu-latest"
          #   version: "1.8"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.7"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.6"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "nightly"
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{runner.os}}-test-${{env.cache-name}}-${{hashFiles('**/Project.toml')}}
          restore-keys: |
            ${{runner.os}}-test-${{env.cache-name}}-
            ${{runner.os}}-test-
            ${{runner.os}}-
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON:
      # - run: |
      #     julia --project=@. -e 'using Pkg; Pkg.add(url="https://github.com/eschnett/GridLayoutBase.jl", rev="patch-1")'
      - uses: julia-actions/julia-runtest@v1
        continue-on-error: ${{matrix.version == 'nightly'}}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
